spring:
  application:
    name: hotsignal

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/hotsignal
    username: root
    password: root

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://prod-host:3306/prod_db
    username: prod_user
    password: prod_pw
